"""phase2_core_domain

Revision ID: 929fabf1334d
Revises: 
Create Date: 2026-03-30 11:35:58.759322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '929fabf1334d'
down_revision: Union[str, None] = 'c2341b14cb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('parcel_id', mysql.CHAR(length=36), nullable=True, comment='Foreign key to parcel (optional)'),
    sa.Column('document_type_id', mysql.CHAR(length=36), nullable=False, comment='Foreign key to document type'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Original filename'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Path to file on filesystem'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='Size of file in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type of file'),
    sa.Column('description', sa.Text(), nullable=True, comment='Document description'),
    sa.Column('document_date', sa.Date(), nullable=True, comment='Document date (issue/recording date)'),
    sa.Column('reference_number', sa.String(length=200), nullable=True, comment='Official reference number'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Number of pages (for PDF)'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 checksum for integrity'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_document_date', 'documents', ['document_date'], unique=False)
    op.create_index('idx_filename', 'documents', ['filename'], unique=False)
    op.create_index('idx_reference_number', 'documents', ['reference_number'], unique=False)
    op.create_index(op.f('ix_documents_document_type_id'), 'documents', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_documents_parcel_id'), 'documents', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_documents_reference_number'), 'documents', ['reference_number'], unique=False)
    op.create_table('tax_records',
    sa.Column('parcel_id', mysql.CHAR(length=36), nullable=False, comment='Foreign key to parcel'),
    sa.Column('assessment_year', sa.String(length=4), nullable=False, comment="Year of tax assessment (e.g., '2024')"),
    sa.Column('assessed_value', sa.Float(), server_default='0.0', nullable=False, comment='Assessed value of parcel for tax purposes'),
    sa.Column('tax_rate_applied', sa.Float(), server_default='0.0', nullable=False, comment='Tax rate applied for this assessment'),
    sa.Column('base_tax_amount', sa.Float(), server_default='0.0', nullable=False, comment='Base tax amount calculated'),
    sa.Column('penalties_amount', sa.Float(), server_default='0.0', nullable=False, comment='Penalties amount if any'),
    sa.Column('total_amount', sa.Float(), server_default='0.0', nullable=False, comment='Total tax amount due (base + penalties)'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='Status of tax record (pending, paid, overdue)'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='Due date for payment'),
    sa.Column('paid_date', sa.Date(), nullable=True, comment='Date when fully paid (if applicable)'),
    sa.Column('payment_reference', sa.String(length=100), nullable=True, comment='Reference for full payment'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Additional notes about tax assessment'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_year', 'tax_records', ['assessment_year'], unique=False)
    op.create_index('idx_due_date', 'tax_records', ['due_date'], unique=False)
    op.create_index('idx_status', 'tax_records', ['status'], unique=False)
    op.create_index('idx_unique_parcel_year', 'tax_records', ['parcel_id', 'assessment_year'], unique=True)
    op.create_index(op.f('ix_tax_records_assessment_year'), 'tax_records', ['assessment_year'], unique=False)
    op.create_index(op.f('ix_tax_records_parcel_id'), 'tax_records', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_tax_records_status'), 'tax_records', ['status'], unique=False)
    op.create_table('physical_locations',
    sa.Column('document_id', mysql.CHAR(length=36), nullable=True, comment='Foreign key to document (optional, for direct document location)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Location name (e.g., 'Main Archive Room', 'Basement Storage')"),
    sa.Column('location_code', sa.String(length=50), nullable=False, comment="Unique location code (e.g., 'ARC-01', 'BSM-02')"),
    sa.Column('building', sa.String(length=100), nullable=True, comment='Building name or number'),
    sa.Column('floor', sa.String(length=50), nullable=True, comment='Floor level'),
    sa.Column('room_number', sa.String(length=50), nullable=True, comment='Room number or identifier'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of location and access instructions'),
    sa.Column('environmental_notes', sa.Text(), nullable=True, comment='Notes about environmental conditions (humidity, temperature)'),
    sa.Column('access_restrictions', sa.Text(), nullable=True, comment='Any access restrictions or security requirements'),
    sa.Column('contact_person', sa.String(length=200), nullable=True, comment='Person responsible for this location'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='Contact phone number'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_building_floor', 'physical_locations', ['building', 'floor'], unique=False)
    op.create_index('idx_location_code', 'physical_locations', ['location_code'], unique=False)
    op.create_index(op.f('ix_physical_locations_document_id'), 'physical_locations', ['document_id'], unique=True)
    op.create_index(op.f('ix_physical_locations_location_code'), 'physical_locations', ['location_code'], unique=True)
    op.create_table('qr_code_registry',
    sa.Column('parcel_id', mysql.CHAR(length=36), nullable=True, comment='Foreign key to parcel (optional)'),
    sa.Column('document_id', mysql.CHAR(length=36), nullable=True, comment='Foreign key to document (optional)'),
    sa.Column('code', sa.String(length=255), nullable=False, comment='Unique QR code string'),
    sa.Column('code_type', sa.String(length=20), nullable=False, comment='Type of entity this QR code points to (parcel, document)'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Path to QR code image file'),
    sa.Column('data_payload', sa.JSON(), nullable=False, comment='JSON data encoded in QR code'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Expiration timestamp (if temporary)'),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True, comment='Last time this QR was scanned'),
    sa.Column('access_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times QR has been accessed'),
    sa.Column('is_revoked', sa.Boolean(), server_default='0', nullable=False, comment='Whether this QR code has been revoked'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='JSON field for additional attributes'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_code_type', 'qr_code_registry', ['code_type'], unique=False)
    op.create_index('idx_expires_at', 'qr_code_registry', ['expires_at'], unique=False)
    op.create_index('idx_is_revoked', 'qr_code_registry', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_code'), 'qr_code_registry', ['code'], unique=True)
    op.create_index(op.f('ix_qr_code_registry_code_type'), 'qr_code_registry', ['code_type'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_document_id'), 'qr_code_registry', ['document_id'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_expires_at'), 'qr_code_registry', ['expires_at'], unique=False)
    op.create_index(op.f('ix_qr_code_registry_parcel_id'), 'qr_code_registry', ['parcel_id'], unique=False)
    op.create_table('tax_payments',
    sa.Column('tax_record_id', mysql.CHAR(length=36), nullable=False, comment='Foreign key to tax record'),
    sa.Column('payment_amount', sa.Float(), nullable=False, comment='Amount paid in this transaction'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Date of payment'),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Method of payment (cash, bank_transfer, check)'),
    sa.Column('payment_reference', sa.String(length=100), nullable=True, comment='External payment reference number'),
    sa.Column('receipt_number', sa.String(length=50), nullable=False, comment='Generated receipt number'),
    sa.Column('received_by', sa.String(length=200), nullable=False, comment='Name/ID of person who received payment'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about payment'),
    sa.Column('is_reversal', sa.Boolean(), server_default='0', nullable=False, comment='Whether this is a reversal of a previous payment'),
    sa.Column('reversed_payment_id', mysql.CHAR(length=36), nullable=True, comment='Reference to reversed payment (if is_reversal=True)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['reversed_payment_id'], ['tax_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_record_id'], ['tax_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_date', 'tax_payments', ['payment_date'], unique=False)
    op.create_index('idx_payment_method', 'tax_payments', ['payment_method'], unique=False)
    op.create_index('idx_receipt_number', 'tax_payments', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_tax_payments_payment_date'), 'tax_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_tax_payments_payment_reference'), 'tax_payments', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_tax_payments_receipt_number'), 'tax_payments', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_tax_payments_tax_record_id'), 'tax_payments', ['tax_record_id'], unique=False)
    op.create_table('storage_cabinets',
    sa.Column('physical_location_id', mysql.CHAR(length=36), nullable=False, comment='Foreign key to physical location (room/building)'),
    sa.Column('cabinet_number', sa.String(length=50), nullable=False, comment="Cabinet identifier (e.g., 'CAB-001')"),
    sa.Column('cabinet_type', sa.String(length=50), server_default='filing', nullable=False, comment="Type of cabinet (e.g., 'filing', 'shelf', 'drawer')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of cabinet contents/location'),
    sa.Column('row_number', sa.Integer(), nullable=True, comment='Row number within location (if applicable)'),
    sa.Column('column_number', sa.Integer(), nullable=True, comment='Column number within location (if applicable)'),
    sa.Column('max_capacity', sa.Integer(), nullable=True, comment='Maximum document capacity'),
    sa.Column('current_count', sa.Integer(), server_default='0', nullable=False, comment='Current number of documents stored'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['physical_location_id'], ['physical_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cabinet_number', 'storage_cabinets', ['cabinet_number'], unique=False)
    op.create_index('idx_cabinet_type', 'storage_cabinets', ['cabinet_type'], unique=False)
    op.create_index('idx_unique_cabinet_per_location', 'storage_cabinets', ['physical_location_id', 'cabinet_number'], unique=True)
    op.create_index(op.f('ix_storage_cabinets_cabinet_number'), 'storage_cabinets', ['cabinet_number'], unique=False)
    op.create_index(op.f('ix_storage_cabinets_physical_location_id'), 'storage_cabinets', ['physical_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_cabinets_physical_location_id'), table_name='storage_cabinets')
    op.drop_index(op.f('ix_storage_cabinets_cabinet_number'), table_name='storage_cabinets')
    op.drop_index('idx_unique_cabinet_per_location', table_name='storage_cabinets')
    op.drop_index('idx_cabinet_type', table_name='storage_cabinets')
    op.drop_index('idx_cabinet_number', table_name='storage_cabinets')
    op.drop_table('storage_cabinets')
    op.drop_index(op.f('ix_tax_payments_tax_record_id'), table_name='tax_payments')
    op.drop_index(op.f('ix_tax_payments_receipt_number'), table_name='tax_payments')
    op.drop_index(op.f('ix_tax_payments_payment_reference'), table_name='tax_payments')
    op.drop_index(op.f('ix_tax_payments_payment_date'), table_name='tax_payments')
    op.drop_index('idx_receipt_number', table_name='tax_payments')
    op.drop_index('idx_payment_method', table_name='tax_payments')
    op.drop_index('idx_payment_date', table_name='tax_payments')
    op.drop_table('tax_payments')
    op.drop_index(op.f('ix_qr_code_registry_parcel_id'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_expires_at'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_document_id'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_code_type'), table_name='qr_code_registry')
    op.drop_index(op.f('ix_qr_code_registry_code'), table_name='qr_code_registry')
    op.drop_index('idx_is_revoked', table_name='qr_code_registry')
    op.drop_index('idx_expires_at', table_name='qr_code_registry')
    op.drop_index('idx_code_type', table_name='qr_code_registry')
    op.drop_table('qr_code_registry')
    op.drop_index(op.f('ix_physical_locations_location_code'), table_name='physical_locations')
    op.drop_index(op.f('ix_physical_locations_document_id'), table_name='physical_locations')
    op.drop_index('idx_location_code', table_name='physical_locations')
    op.drop_index('idx_building_floor', table_name='physical_locations')
    op.drop_table('physical_locations')
    op.drop_index(op.f('ix_tax_records_status'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_parcel_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_assessment_year'), table_name='tax_records')
    op.drop_index('idx_unique_parcel_year', table_name='tax_records')
    op.drop_index('idx_status', table_name='tax_records')
    op.drop_index('idx_due_date', table_name='tax_records')
    op.drop_index('idx_assessment_year', table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_documents_reference_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_parcel_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type_id'), table_name='documents')
    op.drop_index('idx_reference_number', table_name='documents')
    op.drop_index('idx_filename', table_name='documents')
    op.drop_index('idx_document_date', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
