"""empty message

Revision ID: a3bfa1088a59
Revises: ac60d369ef05
Create Date: 2026-06-29 11:40:57.582947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3bfa1088a59'
down_revision: Union[str, None] = 'ac60d369ef05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_ownership_history',
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Foreign key to parcel'),
    sa.Column('owner_name', sa.String(length=500), nullable=False, comment='Name of the owner at this point in time'),
    sa.Column('owner_contact', sa.String(length=500), nullable=True, comment='Contact information for the owner'),
    sa.Column('transfer_date', sa.Date(), nullable=False, comment='Date when ownership was transferred'),
    sa.Column('document_reference', sa.String(length=255), nullable=True, comment='Reference to supporting document (title deed, sale agreement, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about the ownership transfer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Soft delete flag: True if record is active, False if deleted'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parcel_transfer_date', 'parcel_ownership_history', ['parcel_id', 'transfer_date'], unique=False)
    op.create_index(op.f('ix_parcel_ownership_history_parcel_id'), 'parcel_ownership_history', ['parcel_id'], unique=False)
    op.drop_table('spatial_ref_sys')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID of the record that was modified',
               existing_nullable=False)
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='User ID who performed the action',
               existing_nullable=False)
    op.alter_column('audit_logs', 'performed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when action was performed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.alter_column('backup_jobs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('backup_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('backup_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('backup_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('backup_jobs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               comment='UUID primary key',
               existing_nullable=False)
    op.drop_index('ix_backup_jobs_created_at', table_name='backup_jobs')
    op.drop_index('ix_backup_jobs_status', table_name='backup_jobs')
    op.drop_index('ix_backup_jobs_tier', table_name='backup_jobs')
    op.alter_column('backup_verifications', 'backup_job_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('backup_verifications', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('backup_verifications', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('backup_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('backup_verifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               comment='UUID primary key',
               existing_nullable=False)
    op.drop_index('ix_backup_verifications_status', table_name='backup_verifications')
    op.drop_constraint('backup_verifications_backup_job_id_fkey', 'backup_verifications', type_='foreignkey')
    op.alter_column('document_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('document_types', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.drop_constraint('document_types_code_key', 'document_types', type_='unique')
    op.drop_constraint('document_types_name_key', 'document_types', type_='unique')
    op.alter_column('documents', 'parcel_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to parcel (optional)',
               existing_nullable=True)
    op.alter_column('documents', 'document_type_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to document type',
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('land_use_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_use_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_use_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('land_use_categories', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.drop_constraint('land_use_categories_code_key', 'land_use_categories', type_='unique')
    op.drop_constraint('land_use_categories_name_key', 'land_use_categories', type_='unique')
    op.alter_column('parcels', 'parish_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to parish',
               existing_nullable=False)
    op.alter_column('parcels', 'land_use_category_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to land use category',
               existing_nullable=True)
    op.alter_column('parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.execute("ALTER TABLE tax_records ALTER COLUMN status TYPE VARCHAR(20)")
    op.execute("CREATE TYPE taxrecordstatus AS ENUM ('pending', 'paid', 'overdue', 'cancelled')")
    op.execute("ALTER TABLE tax_records ALTER COLUMN status TYPE taxrecordstatus USING status::taxrecordstatus")
    op.execute("ALTER TABLE tax_records ALTER COLUMN status SET DEFAULT 'pending'")
    op.execute("ALTER TABLE tax_records ALTER COLUMN assessment_year TYPE INTEGER USING assessment_year::INTEGER")
    op.alter_column('parcels', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.drop_constraint('parcels_parcel_number_key', 'parcels', type_='unique')
    op.drop_index('idx_parcel_number', table_name='parcels')
    op.create_index('idx_parcel_number', 'parcels', ['parcel_number'], unique=False)
    op.create_index(op.f('ix_parcels_parcel_number'), 'parcels', ['parcel_number'], unique=False)
    op.create_index(op.f('ix_parcels_title_deed_number'), 'parcels', ['title_deed_number'], unique=False)
    op.execute("CREATE INDEX idx_parcels_geometry ON parcels USING gist(geometry_wkb)")
    op.alter_column('parishes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parishes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('parishes', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.drop_constraint('parishes_code_key', 'parishes', type_='unique')
    op.alter_column('physical_locations', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to document (optional, for direct document location)',
               existing_nullable=True)
    op.alter_column('physical_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physical_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physical_locations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('qr_code_registry', 'parcel_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to parcel (optional)',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to document (optional)',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Expiration timestamp (if temporary)',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Last time this QR was scanned',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_code_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_code_registry', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('storage_cabinets', 'physical_location_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to physical location (room/building)',
               existing_nullable=False)
    op.alter_column('storage_cabinets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storage_cabinets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storage_cabinets', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('tax_payments', 'tax_record_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to tax record',
               existing_nullable=False)
    op.alter_column('tax_payments', 'reversed_payment_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Reference to reversed payment (if is_reversal=True)',
               existing_nullable=True)
    op.alter_column('tax_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_payments', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('tax_records', 'parcel_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='Foreign key to parcel',
               existing_nullable=False)
    op.alter_column('tax_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_records', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_comment='UUID primary key',
               existing_nullable=False)
    # ### end Alembic commands ###

    op.execute("DROP INDEX IF EXISTS idx_parcels_geometry")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('tax_records', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_records', 'parcel_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to parcel',
               existing_nullable=False)
    op.alter_column('tax_payments', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('tax_payments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_payments', 'reversed_payment_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Reference to reversed payment (if is_reversal=True)',
               existing_nullable=True)
    op.alter_column('tax_payments', 'tax_record_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to tax record',
               existing_nullable=False)
    op.alter_column('storage_cabinets', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('storage_cabinets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storage_cabinets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('storage_cabinets', 'physical_location_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to physical location (room/building)',
               existing_nullable=False)
    op.alter_column('qr_code_registry', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('qr_code_registry', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_code_registry', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_code_registry', 'last_accessed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Last time this QR was scanned',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Expiration timestamp (if temporary)',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to document (optional)',
               existing_nullable=True)
    op.alter_column('qr_code_registry', 'parcel_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to parcel (optional)',
               existing_nullable=True)
    op.alter_column('physical_locations', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('physical_locations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physical_locations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physical_locations', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to document (optional, for direct document location)',
               existing_nullable=True)
    op.create_unique_constraint('parishes_code_key', 'parishes', ['code'])
    op.alter_column('parishes', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('parishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('parishes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parishes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_parcels_title_deed_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_parcel_number'), table_name='parcels')
    op.drop_index('idx_parcel_number', table_name='parcels')
    op.create_index('idx_parcel_number', 'parcels', ['parcel_number'], unique=True)
    op.create_unique_constraint('parcels_parcel_number_key', 'parcels', ['parcel_number'])
    op.alter_column('parcels', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('parcels', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('parcels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'land_use_category_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to land use category',
               existing_nullable=True)
    op.alter_column('parcels', 'parish_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to parish',
               existing_nullable=False)
    op.create_unique_constraint('land_use_categories_name_key', 'land_use_categories', ['name'])
    op.create_unique_constraint('land_use_categories_code_key', 'land_use_categories', ['code'])
    op.alter_column('land_use_categories', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('land_use_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('land_use_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_use_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'document_type_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to document type',
               existing_nullable=False)
    op.alter_column('documents', 'parcel_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='Foreign key to parcel (optional)',
               existing_nullable=True)
    op.create_unique_constraint('document_types_name_key', 'document_types', ['name'])
    op.create_unique_constraint('document_types_code_key', 'document_types', ['code'])
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('document_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('document_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('backup_verifications_backup_job_id_fkey', 'backup_verifications', 'backup_jobs', ['backup_job_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_backup_verifications_status', 'backup_verifications', ['status'], unique=False)
    op.alter_column('backup_verifications', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('backup_verifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('backup_verifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verifications', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('backup_verifications', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('backup_verifications', 'backup_job_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index('ix_backup_jobs_tier', 'backup_jobs', ['tier'], unique=False)
    op.create_index('ix_backup_jobs_status', 'backup_jobs', ['status'], unique=False)
    op.create_index('ix_backup_jobs_created_at', 'backup_jobs', ['created_at'], unique=False)
    op.alter_column('backup_jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('backup_jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('backup_jobs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('backup_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('backup_jobs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('audit_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: True if record is active, False if deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'performed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when action was performed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='User ID who performed the action',
               existing_nullable=False)
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='UUID of the record that was modified',
               existing_nullable=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID primary key'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='User email address'),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Unique username'),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Full name of user'),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'::character varying"), autoincrement=False, nullable=False, comment='User role (admin, client, viewer)'),
    sa.Column('parish_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='For clients, links to their parish'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Whether user account is active'),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Whether email is verified'),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Last successful login timestamp'),
    sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False, comment='Count of failed login attempts'),
    sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Account locked until this timestamp'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_parcel_ownership_history_parcel_id'), table_name='parcel_ownership_history')
    op.drop_index('idx_parcel_transfer_date', table_name='parcel_ownership_history')
    op.drop_table('parcel_ownership_history')
    # ### end Alembic commands ###
